Update README.md
Running rails-new with sudo causes the following error during the initial 

Step 5/8 : RUN groupadd -g $GROUP_ID app && useradd -u $USER_ID -g app -m app
 ---> Running in 283cd70fd9e4
groupadd: GID '0' already exists
The command '/bin/sh -c groupadd -g $GROUP_ID app && useradd -u $USER_ID -g app -m app' returned a non-zero code: 4
thread 'main' panicked at src/main.rs:41:5:
assertion failed: status.success()